ginameeeBV/bgm-controller

src/components/molecules/VolumeController.tsx
src/components/organisms/VideoCard.tsx

yarn.lock 파일 갱신되는건 최신 main으로 받고나서 없어졌습니다!
따로 globalState를 이용한 확장은 고려하지 않고 일단 작동 되게 해놨습니다!

feat: VideoCard에 비디오 제어 추가

---

src/components/organisms/VideoCard.tsx
src/components/organisms/VideoList.tsx

리스트 내에서 삭제 로직 추가했습니다! 동영상 url 중복 우려가있어 어떻게 할지 애매하네요ㅠㅠ
추가로 동영상 카드 높이값 고정했습니다!

feat: videoList remove 추가

---

src/components/atoms/PauseButton.tsx
src/components/atoms/PlayButton.tsx
src/components/atoms/StopButton.tsx
src/components/molecules/ControlButtons.tsx

feat: ControlButtons 좀 더 잘게 쪼게기

---

src/components/organisms/AddForm.tsx

refactor: 중복 url 추가 안함

---

src/components/organisms/VideoCard.tsx

platerRef의 타입이 any로 되어있어서 수정했습니다!

fix: playerRef 타입 추가

---

src/components/organisms/VideoList.tsx

- 기본 스타일: rgba(0,0,0,0.04)
- hover시 색상 반전

fix: 비디오리스트 삭제 버튼 hover시 background 가 투명한 이슈 수정

---

src/components/organisms/GlobalController.tsx
src/components/organisms/VideoCard.tsx
src/hooks/useVolume.ts
src/stores/videos.ts

fade in/out 적용
- 소리와 관련된 로직 useVolume 훅으로 분리

feat: fade in/out 적용

---

src/components/atoms/MuteButton.tsx
src/components/organisms/GlobalController.tsx
src/components/organisms/VideoCard.tsx
src/hooks/useVolume.ts
src/stores/videos.ts

마이크 버튼 기능 추가
- 말하기를 위한 min volume 세팅기능 추가
- 마이크버튼 선택시 세팅한  min volume 까지 소리 fadeout 되도록 설정

feat: 마이크 버튼 기능 추가

---

src/components/organisms/VideoCard.tsx
src/hooks/useVolume.ts

feat: Fade 효과 비율 조절 추가

---

src/components/organisms/GlobalController.tsx
src/components/organisms/VideoCard.tsx

fix: 동영상 일시 정지 시, currPlayedUrl 체크 추가

---

src/components/atoms/DeleteButton.tsx
src/components/organisms/GlobalController.tsx
src/components/organisms/VideoList.tsx

- ratio input 문구 수정 (fade out ratio -> fade in/out speed)
-  근데 문구가 맞는지에 대한 고민이 있음. speed of fade in/out? 이 맞는걸까?
- DeleteButton atom 생성

refactor: ratio input 문구 수정, DeleteButton 분리

---

src/components/molecules/VolumeController.tsx
src/components/organisms/VideoCard.tsx

필요없다고 판단한 fadeout button 제거
- 일시정지 시, fadeout 됨!

refactor: fadeout button 제거

---

src/components/molecules/EmptyList.tsx

fix: 안내문구 오탈자 수정

---

src/components/organisms/VideoCard.tsx
src/hooks/useVolume.ts

- masterVolume을 maxVolume으로 사용하도록 수정
- fade out / in 되면서 최대값, 최소값을 미묘하게 벗어나는 이슈 수정 (fade out될때 가끔 음수값이 세팅됨)

feat: masterVolum을 maxVolume으로 사용하도록 수정

---

src/components/atoms/StopButton.tsx
src/components/molecules/ControlButtons.tsx
src/components/organisms/VideoCard.tsx

비디오 재생상태에 따라 버튼 disabled 되도록 수정

feat: 비디오 재생상태에 따라 버튼 disabled 되도록 수정

---

src/components/molecules/VolumeController.tsx
src/components/organisms/GlobalController.tsx
src/components/templates/MainTemplate.tsx

- input type = number 가 오히려 입력에 불편한 느낌이 있음, type을 text로 수정후 number 만 입력받도록 수정
- fix: header, footer VideoCard에 덮이는 이슈 수정

feat: ux 개선

---

src/components/organisms/GlobalController.tsx

fix: input type 변경 누락된 부분 추가

---

src/components/organisms/GlobalController.tsx

fix: 부조인지화 버튼 수정

---

src/components/atoms/VideoTimeBar.tsx
src/components/organisms/VideoCard.tsx

feat: video time bar 적용

---

src/components/atoms/LoopCheckBox.tsx

feat: loopCheckBox 해제 시 스타일 변경

---

src/components/organisms/GlobalController.tsx
src/hooks/useVolume.ts
src/stores/videos.ts

마이크켜져있으면 maxVolume 값 minVolumeForSpeaking 으로 사용

fix: maxVolume 이슈
